config/routes.rb
Rails.application.routes.draw do

  resources :products
  get 'clientes', to: 'admin_page#clientes'
  get 'new', to: 'products#new'
  get 'cake_shop', to: 'categories#cake_shop'
  get 'drinks', to:'categories#drinks'
  get 'candy_store', to: 'categories#candy_store'
  get 'admin', to: 'admin_page#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  # root 'static_pages#home'
  post "create" => 'static_pages#create'
  root to: "static_pages#home"
  get 'help' => 'static_pages#help'
  get 'products' => 'static_pages#products'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_page_controller.rb
class AdminPageController < ApplicationController
  def index
  end

  def clientes
    @users = User.all.order("created_at")  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def cake_shop
  end

  def drinks
  end

  def candy_store
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :body, :price, :quantity)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :lastname, :mobile, :address, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :lastname, :mobile, :address, :password, :password_confirmation, :current_password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @contact = Contact.new
  end

  def create
    @contact= Contact.new(contact_params)
    if @contact.save
      NotificationMailer.welcome_email(@contact).deliver_now!
      redirect_to root_path, notice: 'Mensaje enviado'
    else
      render:home
    end
  end

  def help
  end

  def products
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :reason, :message)
  end
end

app/helpers/admin_page_helper.rb
module AdminPageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin_page/_sidebar.html.erb
<aside class="menu-sidebar d-none d-lg-block">
    <div class="logo">
        <a href="#">
            <img src="images/icon/logo.png" alt="Cool Admin" />
        </a>
    </div>
    <div class="menu-sidebar__content js-scrollbar1">
        <nav class="navbar-sidebar">
            <ul class="list-unstyled navbar__list">
                <li class="active has-sub">
                    <a class="js-arrow" href="#">
                        <i class="fas fa-tachometer-alt"></i>Bienvenido</a>
                    <ul class="list-unstyled navbar__sub-list js-sub-list">
                        <li>
                            <a href="index.html"> Bienvenido</a>
                        </li>
                        <li>
                            <a href="index2.html">Bienvenido</a>
                        </li>
                        <li>
                            <a href="index3.html">Bienvenido</a>
                        </li>
                        <li>
                            <a href="index4.html">Bienvenido</a>
                        </li>
                    </ul>
                </li>
                <li>
                    

                        <%= link_to "Crear productos", new_path, class:"fas fa-chart-ba" %>
                </li>
                <li>

                        <%= link_to "Ver clientes", clientes_path, class:"fas fa-table" %>
                </li>
                <li>
                    <a href="form.html">
                        <i class="far fa-check-square"></i>Estadisticos</a>
                </li>
                <li>
                    <a href="calendar.html">
                        <i class="fas fa-calendar-alt"></i>Calendar</a>
                </li>
                <li>
                    <a href="map.html">
                        <i class="fas fa-map-marker-alt"></i>Maps</a>
                </li>
                <li class="has-sub">
                    <a class="js-arrow" href="#">
                        <i class="fas fa-copy"></i>Pages</a>
                    <ul class="list-unstyled navbar__sub-list js-sub-list">
                        <li>
                            <a href="login.html">Login</a>
                        </li>
                        <li>
                            <a href="register.html">Register</a>
                        </li>
                        <li>
                            <a href="forget-pass.html">Forget Password</a>
                        </li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a class="js-arrow" href="#">
                        <i class="fas fa-desktop"></i>UI Elements</a>
                    <ul class="list-unstyled navbar__sub-list js-sub-list">
                        <li>
                            <a href="button.html">Button</a>
                        </li>
                        <li>
                            <a href="badge.html">Badges</a>
                        </li>
                        <li>
                            <a href="tab.html">Tabs</a>
                        </li>
                        <li>
                            <a href="card.html">Cards</a>
                        </li>
                        <li>
                            <a href="alert.html">Alerts</a>
                        </li>
                        <li>
                            <a href="progress-bar.html">Progress Bars</a>
                        </li>
                        <li>
                            <a href="modal.html">Modals</a>
                        </li>
                        <li>
                            <a href="switch.html">Switchs</a>
                        </li>
                        <li>
                            <a href="grid.html">Grids</a>
                        </li>
                        <li>
                            <a href="fontawesome.html">Fontawesome Icon</a>
                        </li>
                        <li>
                            <a href="typo.html">Typography</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</aside>

app/views/admin_page/clientes.html.erb
<%= render 'admin_page/sidebar'%>
<div class="page-container">

    <!-- MAIN CONTENT-->
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">


                <div class="row">
                    <div class="col-lg-9">
                        <h2 class="title-1 m-b-25">Usuarios registrados</h2>
                        <div class="table-responsive table--no-card m-b-40">
                            <table class="table table-borderless table-striped table-earning">
                                <thead>
                                    <tr>
                                        <th>Email</th>
                                        <th>Nombre</th>
                                        <th>Telefono</th>
                                        <th class="text-right">direccion</th>
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                  <% @users.each do |user|%>
                                    <tr>
                                        <td><%= user.email%></td>
                                        <td><%= user.name%></td>
                                        <td><%= user.mobile%></td>
                                        <td><%= user.address%></td>

                                    </tr>
                                  <%end%>

                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>


            </div>
        </div>
    </div>
    <!-- END MAIN CONTENT-->
    <!-- END PAGE CONTAINER-->
</div>

app/views/categories/cake_shop.html.erb
<br>
<br>
<br>

<h3 class="display-6">Reposteria</h3>
<div class="row  abs-center">
  <div class="col-sm-3 ">
      <div class="card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'reposteria.jpg'%>" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">Producto1</h5>
          <p class="card-text">Informacion de producto.</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
    </div>
  </div>

  <div class="col-sm-3">
      <div class="card border-info mb-3" style="width: 18rem; ">
      <img src="<%= asset_path 'dulceria.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">Producto2</h5>
          <p class="card-text">Informacion del producto.</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
    </div>
  </div>
  <div class="col-sm-3">
      <div class="card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'bebidas.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">Producto3</h5>
          <p class="card-text">Informacion del producto</p>
          <a href="#" class="btn btn-primary">comprar</a>
        </div>
    </div>
  </div>
</div>

app/views/categories/candy_store.html.erb
<br>
<br>
<br>

<h3 class="display-6">DULCERIA</h3>
<div class="row  abs-center">
  <div class="col-sm-3 ">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'reposteria.jpg'%>" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">REPOSTERIA</h5>
          <p class="card-text">Disfruta de nuestra gran variedad de productos como pan caliente entre otros productos.</p>
          <a href="#" class="btn btn-primary">VER MENU</a>
        </div>
    </div>
  </div>

  <div class="col-sm-3">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'dulceria.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">DULCERIA</h5>
          <p class="card-text">Gosate nuestra gran variedad de dulces y caramelos disponibles para toda ocasion.</p>
          <a href="#" class="btn btn-primary">VER MENU</a>
        </div>
    </div>
  </div>
  <div class="col-sm-3">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'bebidas.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">BEBIDAS</h5>
          <p class="card-text">Disfruta de nuestras ricas y deliciosas bebidas las cuales te refrescaran en tu venida</p>
          <a href="#" class="btn btn-primary">VER MENU</a>
        </div>
    </div>
  </div>
</div>

app/views/categories/drinks.html.erb
<br>
<br>
<br>

<h3 class="display-6">Bebidas</h3>
<div class="row  abs-center">
  <div class="col-sm-3 ">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'reposteria.jpg'%>" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">REPOSTERIA</h5>
          <p class="card-text">Disfruta de nuestra gran variedad de productos como pan caliente entre otros productos.</p>
          <a href="#" class="btn btn-primary">VER MENU</a>
        </div>
    </div>
  </div>

  <div class="col-sm-3">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'dulceria.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">DULCERIA</h5>
          <p class="card-text">Gosate nuestra gran variedad de dulces y caramelos disponibles para toda ocasion.</p>
          <a href="#" class="btn btn-primary">VER MENU</a>
        </div>
    </div>
  </div>
  <div class="col-sm-3">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'bebidas.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">BEBIDAS</h5>
          <p class="card-text">Disfruta de nuestras ricas y deliciosas bebidas las cuales te refrescaran en tu venida</p>
          <a href="#" class="btn btn-primary">VER MENU</a>
        </div>
    </div>
  </div>
</div>

app/views/homes/index.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="<%= asset_path 'producto5.jpg'%>" class="d-block w-100" height="300px">
    </div>
    <div class="carousel-item">
      <img src="<%= asset_path 'producto4.jpg'%>" class="d-block w-100" height="300px">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Panaderia</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav w-100  justify-content-center">
      <li class="nav-item active">
        <%= link_to "Home",  root_path, class:"nav-link" %>

      </li>
      <li class="nav-item">
        <%= link_to "productos",  products_path, class:"nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categorias
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <%= link_to "Categoria1",  cake_shop_path, class: "dropdown-item" %>

          <%= link_to "Categoria2",  drinks_path, class: "dropdown-item" %>

          <%= link_to "Categoria3",  candy_store_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>

  </div>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <% if !user_signed_in? %>
      <%= link_to 'Inicar sesion', new_user_session_path, class:'btn btn-outline-primary my-2 my-sm-0 mr-2' %>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to destroy_user_session_path, method: :delete do %>
          <button class="btn btn-outline-dark my-2 my-sm-0">Cerrar sesion</button>
      <% end %>
    <% end %>

  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> |panaderia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Vendor JS       -->
    <script src="vendor/slick/slick.min.js">
    </script>
    <script src="vendor/wow/wow.min.js"></script>
    <script src="vendor/animsition/animsition.min.js"></script>
    <script src="vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="vendor/circle-progress/circle-progress.min.js"></script>
    <script src="vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="vendor/select2/select2.min.js">
    </script>

    <% flash.each do |key, value|%>
      <div class="alert alert-success alert-dismissible" role="alert">
        <div class="alert-message">
          <strong><%= key %></strong>
          <%= value %>
        </div>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>



    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>



<!--<h1>Products</h1>

<table>
  <thead>
    <tr >
      <th>Title</th>
      <th>Body</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr >
        <td><%= product.title %></td>
        <td><%= product.body %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>-->


<div class="row">
    <div class="col-lg-9">
        <h2 class="title-1 m-b-25">Productos regitrados</h2>
        <div class="table-responsive table--no-card m-b-40">
            <table class="table table-borderless table-striped table-earning">
                <thead>
                    <tr>
                      <th>Title</th>
                      <th>Body</th>
                      <th>Price</th>
                      <th>Quantity</th>
                        <th class="text-right">mostrar</th>
                        <th class="text-right">modificar</th>
                        <th class="text-right">eliminar</th>

                    </tr>
                </thead>
                <tbody>

                  <% @products.each do |product| %>
                    <tr >
                      <td><%= product.title %></td>
                      <td><%= product.body %></td>
                      <td><%= product.price %></td>
                      <td><%= product.quantity %></td>
                      <td><%= link_to 'Show', product %></td>
                      <td><%= link_to 'Edit', edit_product_path(product) %></td>
                      <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>


                </tbody>
            </table>
        </div>
    </div>

</div>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<br>
<br>
<br>

<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @product.body %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/help.html.erb
<% provide(:title, "Ayuda") %>
<h1>StaticPages#help</h1>

<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="<%= asset_path 'producto5.jpg'%>" class="d-block w-100" height="300px">
    </div>
    <div class="carousel-item">
      <img src="<%= asset_path 'producto4.jpg'%>" class="d-block w-100" height="300px">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!- presente login ->
<div class="jumbotron">
  <% if user_signed_in? %>
    <h1 class="display-4">BIENVENIDO <%= current_user.name %> <%= current_user.lastname %></h1>
    <% else %>
    <h1 class="display-4">BIENVENIDO</h1>
  <% end %>

  <p class="lead">pan caliente es una de las mejores panaderias del pais que se enorgullece de su gran avance a nivel nacional .</p>
  <hr class="my-4">
  <p>Registrate para disfrutar de una gran variesdad y esquesites de producto en pan caliente</p>
  <%= link_to "Ver perfil",  admin_path, class:"btn btn-primary btn-lg" %>
</div>
<!- fin de login->

<h1 class="display-4 text-center"> Nuestras Categorias </h1>
<div class="row  abs-center">
  <div class="col-sm-3 ">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'reposteria.jpg'%>" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">Categoria 1</h5>
          <p class="card-text">Descripcion de Categoria.</p>
          <%= link_to "Ver Categoria",  cake_shop_path, class:"btn btn-primary " %>
        </div>
    </div>
  </div>

  <div class="col-sm-3">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'dulceria.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">Categoria2</h5>
          <p class="card-text">Descripcion de la categoria.</p>
          <%= link_to "Ver Categoria",  candy_store_path, class:"btn btn-primary " %>
        </div>
    </div>
  </div>
  <div class="col-sm-3">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'bebidas.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">Categoria3</h5>
          <p class="card-text">Descripcion de categoria</p>
          <%= link_to "Ver Categoria",  drinks_path, class:"btn btn-primary " %>
        </div>
    </div>
  </div>
</div>

<h1 class="display-4 text-center"> Nuestros Mejores Productos</h1>
<div class="row  abs-center">
  <div class="col-sm-3 ">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'reposteria.jpg'%>" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">Producto1</h5>
          <p class="card-text">Informacion del productos.</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
    </div>
  </div>

  <div class="col-sm-3">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'dulceria.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">Producto2</h5>
          <p class="card-text">Informacion del producto.</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
    </div>
  </div>
  <div class="col-sm-3">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'bebidas.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">Prodcuto3</h5>
          <p class="card-text">Informacion del producto</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
    </div>
  </div>
</div>

<h3 class="display-6">Categoria1</h3>
<div class="row  abs-center">
  <div class="col-sm-3 ">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'reposteria.jpg'%>" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">Producto1</h5>
          <p class="card-text">Informacion del producto.</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
    </div>
  </div>

  <div class="col-sm-3">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'dulceria.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">Prodcuto2</h5>
          <p class="card-text">Informacion del prodcuto.</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
    </div>
  </div>
  <div class="col-sm-3">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'bebidas.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">Producto3</h5>
          <p class="card-text">Informacion del producto</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
    </div>
  </div>
</div>

<h3 class="display-6">Categoria2</h3>
<div class="row  abs-center">
  <div class="col-sm-3 ">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'reposteria.jpg'%>" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">Producto1</h5>
          <p class="card-text">Informacion del producto.</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
    </div>
  </div>

  <div class="col-sm-3">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'dulceria.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">Producto2</h5>
          <p class="card-text">Informacion del producto</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
    </div>
  </div>
  <div class="col-sm-3">
      <div class="card card border-info mb-3" style="width: 18rem;">
      <img src="<%= asset_path 'bebidas.jpg'%>" class="card-img-top" height="130px">
        <div class="card-body">
          <h5 class="card-title">Producto3</h5>
          <p class="card-text">Informacion del producto</p>
          <a href="#" class="btn btn-primary">Comprar</a>
        </div>
    </div>
  </div>
</div>

<%= render 'contact' %>